/*
 * File: app/store/store.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.store', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'store',
            data: [
                {
                    name: 'filter one',
                    data: 10
                },
                {
                    name: 'filter two',
                    data: 7
                },
                {
                    name: 'filter three',
                    data: 5
                },
                {
                    name: 'filter four',
                    data: 2
                },
                {
                    name: 'filter five',
                    data: 27
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'data'
                }
            ]
        }, cfg)]);
    }
});