/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    height: 600,
                    title: 'Clicking legend ...',
                    items: [
                        {
                            xtype: 'chart',
                            height: 250,
                            id: 'pieChart',
                            width: 400,
                            animate: true,
                            insetPadding: 20,
                            store: 'store',
                            theme: 'Base',
                            series: [
                                {
                                    type: 'pie',
                                    highlight: {
                                        segment: {
                                            margin: 20
                                        }
                                    },
                                    label: {
                                        field: 'name',
                                        display: 'rotate',
                                        contrast: true,
                                        font: '16px Arial'
                                    },
                                    showInLegend: true,
                                    tips: {
                                        trackMouse: true,
                                        width: 140,
                                        height: 28,
                                        renderer: function(storeItem, item) {
                                            var total = 0;
                                            var store = Ext.getStore('store');
                                            store.each(function(rec) {
                                                total += rec.get('data');
                                            });
                                            this.setTitle(storeItem.get('name') + ': ' + Math.round(storeItem.get('data') / total * 100) + '%');
                                        }
                                    },
                                    angleField: 'data'
                                }
                            ],
                            legend: {
                                enableItemEvents: false,
                                position: 'right'
                            },
                            listeners: {
                                afterrender: {
                                    fn: me.onPieChartAfterRender,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onPieChartAfterRender: function(component, eOpts) {
        Ext.define('MyApp.override.pieChart.LegendItem', {
            override: 'Ext.chart.LegendItem',
            onMouseDown: function() {
                console.log('onMouseDown override');
                alert(this.getLabelText());
                this.callOverridden();
                /*
                var me = this;
                if (me.legend.enableItemEvents !== false) {

                me.callParent(arguments);
                }
                */
            }
        });
    }

});